"""Evidence-driven, model-agnostic material discovery orchestration."""

from .engine import DiscoveryEngine
from .alphagenome import (
    AlphaGenomeClient,
    AlphaGenomeEvaluation,
    GenomicEvaluationPipeline,
    GenomicMode,
    VariantCandidate,
    build_alphagenome_from_environment,
    evaluate_genomic_candidates,
)
from .evidence_fusion import EvidenceDrivenFusionBackend
from .configured_fusion import (
    build_fusion_backend_from_environment,
    build_generator_from_environment,
    build_generators_from_environment,
)
from .fusion_adapters import HttpExpertEncoder, HttpFusionCandidateGenerator, RemoteFusionBackend
from .fusion_exploration import (
    AdaptiveGenerationScheduler,
    CandidatePool,
    CandidatePoolEntry,
    DeterministicExplorationSelector,
    ExcludedCandidate,
    ExpertEvidenceConflict,
    ExpertEvidenceEnvelope,
    ExpertEvidenceIntegrityError,
    ExpertEvidenceStore,
    ExplorationBranch,
    ExplorationBranchResult,
    ExplorationError,
    ExplorationSelection,
    GenerationControlScheduler,
    SchedulerDecision,
    SchedulerObservation,
    SelectedCandidate,
    StoredExpertEvidence,
)
from .fusion_loop import FusionLoopRunner, WorkspaceBenchmarkRunner
from .fusion_protocols import ExpertEncoder, FusionBackend, FusionCandidateGenerator
from .fusion_registry import ExpertRegistry
from .fusion_runtime import FusionRuntime
from .fusion_search import (
    FusionSearchError,
    FusionSearchReport,
    FusionSearchRunner,
    FusionSearchStatus,
    PersistedFusionSearchReport,
    SearchBranchFailurePayload,
    SearchBranchFailureRecord,
    SearchBranchReport,
    SearchCandidateRecord,
    SearchControlAttemptRecord,
    SearchControlPoint,
    SearchControlSweep,
    SearchCycleRecord,
    SearchObservationContext,
    SearchObservationProvider,
    RankedSearchCandidate,
    SearchRepresentationArtifactEncoding,
    SearchRepresentationArtifactRef,
    SearchRoundRecord,
)
from .literature_rag import (
    EvidenceBranch,
    EvidenceBranchAssignment,
    EvidenceBranchKind,
    EvidenceClaim,
    EvidenceGraph,
    JsonEvidenceIndex,
    LiteratureEvidencePolicy,
    LiteratureRagPipeline,
    LiteratureRecord,
    LiteratureSource,
    MultiSourceLiteratureRetriever,
    OpenAICompatibleRagModel,
    PromptSearchPlanner,
    RagEvidenceBundle,
    RagSearchPlan,
    build_literature_rag_from_environment,
    load_evidence_bundle,
)
from .model_adapters import LocalDiscoveryModel, RemoteDiscoveryModel
from .stage_rag import (
    RagStage,
    StageAwareMultiRag,
    StageAwareRagRouter,
    StageEvidence,
    StageEvidenceStatus,
    StageRagQuery,
    StageRoute,
)
from .protocols import DiscoveryModel

__version__ = "0.4.0"

__all__ = [
    "AlphaGenomeClient",
    "AlphaGenomeEvaluation",
    "GenomicEvaluationPipeline",
    "AdaptiveGenerationScheduler",
    "CandidatePool",
    "CandidatePoolEntry",
    "DeterministicExplorationSelector",
    "DiscoveryEngine",
    "DiscoveryModel",
    "EvidenceDrivenFusionBackend",
    "EvidenceBranch",
    "EvidenceBranchAssignment",
    "EvidenceBranchKind",
    "EvidenceClaim",
    "EvidenceGraph",
    "JsonEvidenceIndex",
    "LiteratureEvidencePolicy",
    "LiteratureRagPipeline",
    "LiteratureRecord",
    "LiteratureSource",
    "MultiSourceLiteratureRetriever",
    "OpenAICompatibleRagModel",
    "PromptSearchPlanner",
    "RagEvidenceBundle",
    "RagSearchPlan",
    "build_literature_rag_from_environment",
    "load_evidence_bundle",
    "ExcludedCandidate",
    "ExpertEncoder",
    "ExpertEvidenceConflict",
    "ExpertEvidenceEnvelope",
    "ExpertEvidenceIntegrityError",
    "ExpertEvidenceStore",
    "ExpertRegistry",
    "ExplorationBranch",
    "ExplorationBranchResult",
    "ExplorationError",
    "ExplorationSelection",
    "FusionBackend",
    "FusionCandidateGenerator",
    "FusionLoopRunner",
    "FusionRuntime",
    "FusionSearchError",
    "FusionSearchReport",
    "FusionSearchRunner",
    "FusionSearchStatus",
    "GenerationControlScheduler",
    "GenomicMode",
    "HttpExpertEncoder",
    "HttpFusionCandidateGenerator",
    "LocalDiscoveryModel",
    "PersistedFusionSearchReport",
    "RemoteDiscoveryModel",
    "RagStage",
    "StageAwareMultiRag",
    "StageAwareRagRouter",
    "StageEvidence",
    "StageEvidenceStatus",
    "StageRagQuery",
    "StageRoute",
    "RemoteFusionBackend",
    "SchedulerDecision",
    "SchedulerObservation",
    "SearchBranchFailurePayload",
    "SearchBranchFailureRecord",
    "SearchBranchReport",
    "SearchCandidateRecord",
    "SearchControlAttemptRecord",
    "SearchControlPoint",
    "SearchControlSweep",
    "SearchCycleRecord",
    "SearchObservationContext",
    "SearchObservationProvider",
    "RankedSearchCandidate",
    "SearchRepresentationArtifactEncoding",
    "SearchRepresentationArtifactRef",
    "SearchRoundRecord",
    "SelectedCandidate",
    "StoredExpertEvidence",
    "WorkspaceBenchmarkRunner",
    "VariantCandidate",
    "evaluate_genomic_candidates",
    "build_alphagenome_from_environment",
    "build_fusion_backend_from_environment",
    "build_generator_from_environment",
    "build_generators_from_environment",
    "__version__",
]
